#!/usr/bin/env bash
# sync_vulns.sh — Fetch known iOS framework vulnerabilities from OSV.dev and
# write them to data/framework_vulns.yaml in the format expected by Pavise.
#
# Usage:
#   ./scripts/sync_vulns.sh             # writes data/framework_vulns.yaml
#   ./scripts/sync_vulns.sh --dry-run   # prints to stdout instead
#
# Requirements: curl, jq (brew install jq)
#
# OSV.dev ecosystem IDs used:
#   CocoaPods  — pod names used by iOS frameworks
#   SwiftURL   — Swift Package Index / SPM
#
# The output format matches data/framework_vulns.yaml:
#
#   - name: Alamofire
#     bundle_id_prefix: com.alamofire
#     affected_below: "5.9.1"
#     cve: CVE-2024-XXXXX
#     severity: high
#     description: "..."
#     owasp_mobile: M5
#     remediation: "Update to 5.9.1 or later."

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$REPO_ROOT/data/framework_vulns.yaml"
DRY_RUN=0

for arg in "$@"; do
  [[ "$arg" == "--dry-run" ]] && DRY_RUN=1
done

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install with: brew install jq" >&2
  exit 1
fi

if ! command -v curl &>/dev/null; then
  echo "Error: curl is required." >&2
  exit 1
fi

# iOS/Apple ecosystem packages of interest on OSV.dev
# Format: "ecosystem:package_name:bundle_id_prefix:friendly_name"
PACKAGES=(
  "CocoaPods:Alamofire:com.alamofire:Alamofire"
  "CocoaPods:AFNetworking:com.alamofire.AFNetworking:AFNetworking"
  "CocoaPods:SDWebImage:com.sdwebimage:SDWebImage"
  "CocoaPods:Kingfisher:com.onevcat.Kingfisher:Kingfisher"
  "CocoaPods:Firebase:com.google.firebase:Firebase"
  "CocoaPods:GoogleSignIn:com.google.googlesignin:GoogleSignIn"
  "CocoaPods:SwiftyJSON:com.swiftyjson:SwiftyJSON"
  "CocoaPods:Realm:io.realm:Realm"
  "CocoaPods:CocoaLumberjack:com.cocoalumberjack:CocoaLumberjack"
  "CocoaPods:Braintree:com.braintreepayments:Braintree"
  "CocoaPods:Stripe:com.stripe:Stripe"
  "CocoaPods:OpenSSL-Universal:com.github.krzyzanowskim:OpenSSL"
  "CocoaPods:Charts:com.danielgindi:Charts"
  "CocoaPods:Lottie:com.airbnb.lottie:Lottie"
  "CocoaPods:Sentry:io.sentry:Sentry"
  "CocoaPods:FBSDKCoreKit:com.facebook.sdk:FacebookSDK"
  "CocoaPods:AppsFlyerFramework:com.appsflyer:AppsFlyer"
  "CocoaPods:Adjust:com.adjust.sdk:Adjust"
  "CocoaPods:Mixpanel:com.mixpanel:Mixpanel"
  "CocoaPods:TikTokOpenSDKCore:com.tiktok:TikTokSDK"
)

TMP=$(mktemp)
echo "# data/framework_vulns.yaml" > "$TMP"
echo "# Auto-generated by scripts/sync_vulns.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$TMP"
echo "# DO NOT EDIT MANUALLY — re-run the script to refresh." >> "$TMP"
echo "" >> "$TMP"

TOTAL=0
FOUND=0

for entry in "${PACKAGES[@]}"; do
  IFS=: read -r ecosystem pkg bundle_prefix friendly_name <<< "$entry"
  TOTAL=$((TOTAL + 1))

  response=$(curl -s --max-time 10 \
    -X POST "https://api.osv.dev/v1/query" \
    -H "Content-Type: application/json" \
    -d "{\"package\": {\"ecosystem\": \"$ecosystem\", \"name\": \"$pkg\"}}" \
    2>/dev/null) || { echo "  Warning: failed to query OSV for $pkg" >&2; continue; }

  vuln_count=$(echo "$response" | jq '.vulns | length' 2>/dev/null || echo 0)
  if [[ "$vuln_count" == "0" ]] || [[ -z "$vuln_count" ]]; then
    continue
  fi

  echo "  Found $vuln_count vulnerability/vulnerabilities for $friendly_name" >&2

  while IFS= read -r vuln_json; do
    id=$(echo "$vuln_json" | jq -r '.id // "UNKNOWN"')
    summary=$(echo "$vuln_json" | jq -r '.summary // .details // "No description available"' | head -c 200 | tr '\n' ' ')
    severity_raw=$(echo "$vuln_json" | jq -r '.severity[0].score // .database_specific.severity // "MODERATE"' 2>/dev/null | tr '[:lower:]' '[:upper:]')

    # Map CVSS text to pavise severity
    case "$severity_raw" in
      CRITICAL|HIGH|9*|10*) sev="high" ;;
      MODERATE|MEDIUM|7*|8*) sev="warning" ;;
      *) sev="info" ;;
    esac

    # Extract the fixed version (first range with a fixed version)
    fixed_version=$(echo "$vuln_json" | jq -r '
      .affected[]?.ranges[]?
      | select(.type == "SEMVER" or .type == "ECOSYSTEM")
      | .events[]?
      | select(.fixed != null)
      | .fixed
    ' 2>/dev/null | head -1)

    [[ -z "$fixed_version" ]] && fixed_version="unknown"

    # Derive affected_below from fixed version
    affected_below="$fixed_version"

    cat >> "$TMP" <<YAML
- name: $friendly_name
  bundle_id_prefix: $bundle_prefix
  affected_below: "$affected_below"
  cve: $id
  severity: $sev
  description: "$summary"
  owasp_mobile: M9
  remediation: "Update $friendly_name to $fixed_version or later to remediate $id."

YAML

    FOUND=$((FOUND + 1))

  done < <(echo "$response" | jq -c '.vulns[]' 2>/dev/null)

done

echo "" >&2
echo "Sync complete: $FOUND entries written from $TOTAL packages queried." >&2

mkdir -p "$(dirname "$OUT_FILE")"

if [[ "$DRY_RUN" == "1" ]]; then
  cat "$TMP"
else
  cp "$TMP" "$OUT_FILE"
  echo "Written to $OUT_FILE" >&2
fi

rm -f "$TMP"
